version: CI-Build-{build}
max_jobs: 1
image: Visual Studio 2017
before_build:
  - nuget restore Borzoo.sln
build:
  project: Borzoo.sln
  verbosity: normal
test:
  assemblies:
    - '**\*.Tests*.dll'
