image: Visual Studio 2017

install:
  - git submodule update --init --recursive

before_build:
  - nuget restore Borzoo.sln

configuration:
  - Debug
  - Release

build:
  project: Borzoo.sln

test: off
