image: Visual Studio 2017

before_build:
  - nuget restore Borzoo.sln

configuration:
  - Debug
  - Release

build:
  project: Borzoo.sln

after_build:
  - cmd: cd test/UnitTests
  - cmd: dotnet test --no-build --configuration $(configuration) --verbosity normal

test: off
