version: '2'

services:

  borzoo.web:
    container_name: borzoo.web
    build:
      context: ../../src/Borzoo.Web/bin/publish
      dockerfile: Borzoo.Web.Dockerfile
      args: 
        - ASPNETCORE_ENVIRONMENT
    volumes:
      - /var/zevere/borzoo/:/app/data/
    networks:
      - borzoo

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - borzoo.web
    networks:
      - borzoo

networks: 
  borzoo:
    driver: bridge
